In [1]:
import array as arr
a=arr.array ('i',[1,2,3])
a

array('i', [1, 2, 3])

In [2]:
b=arr.array('i',[4,2,3])
b

array('i', [4, 2, 3])

In [3]:
a[1:]

array('i', [2, 3])

In [6]:
a[::-1]

array('i', [4, 3, 2, 1])

In [7]:
a.append(4)
a

array('i', [1, 2, 3, 4, 4])

In [8]:
a.pop()

4

In [11]:
a.remove(3)
a

array('i', [1, 2, 4])

In [12]:
for i in a:
    print(i,end=" ")

1 2 4 

# NUMPY


Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\users\manas\appdata\local\programs\python\python38-32\python.exe -m pip install --upgrade pip' command.


NameError: name 'np' is not defined

IndentationError: unexpected indent (<ipython-input-4-48cd70d7aaab>, line 2)

# NUMPY

In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\users\manas\appdata\local\programs\python\python38-32\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])   #max\min
print(a.min())
print(a.max())
print(a.sum())

1
3
6


In [5]:
import numpy as np   #ndim
a=np.array ([(1,2,3),(4,5,6)])
print(a.ndim)

2


In [6]:
import numpy as np       #itemsize
a=np.array([(1,2,3)])
print(a.itemsize)

4


In [7]:
import numpy as np     #linspace
a=np.linspace(1,3,10)
print(a)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [9]:
import numpy as np        #python numpy array v/s list
import time 
import sys 
S= range(1000)
print(sys.getsizeof(5)*len(S))

d=np.arange(1000)
print(d.size*d.itemsize)

14000
4000


In [10]:
import numpy as np       #square root & standard deviation
a=np.array([(1,2,3),(3,4,5)])
print(np.sqrt(a))
print(np.std(a))

[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]
1.2909944487358056


In [11]:
import numpy as np     #ravel
x=np.array([(1,2,3),(3,4,5)])
print(x.ravel())

[1 2 3 3 4 5]


In [12]:
import numpy as np         #vertical & horizantal stacking
x=np.array([(1,2,3),(3,4,5)])
y=np.array([(1,2,3),(3,4,5)])
print(np.vstack((x,y)))
print(np.hstack((x,y)))

[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]
[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]


In [13]:
a=np.array([(1,2,3),(3,4,5)])       #sum
print(a.sum(axis=0))

[4 6 8]


In [15]:
import numpy as np   #slicing
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[0,2])

3


In [17]:
import numpy as np        #slicing
a=np.array([(8,9),(10,11),(12,13)])
print(a[0:2,1])

[ 9 11]


In [18]:
import numpy as np     #slicing
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[0:,2])

[3 5]


In [22]:
import numpy as np     #reshape
a=np.array([(8,9,10),(11,12,13)])
print(a)
a=a.reshape(3,2)
print(a)



[[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]


In [23]:
import numpy as np     #size & shape
a=np.array([(1,2,3,4,5,6)])
print(a.size)
print(a.shape)


6
(1, 6)


In [24]:
import numpy as np      #dtype
a=np.array([(1,2,3)])
print(a.dtype)

int32
